import { Task } from './types'

export const SEED_TASKS: Task[] = [
  {
    id: 'task_001',
    title: 'Клиент «Симонов Кирилл Андреевич»: Лид',
    description: 'Довести клиента до следующей стадии цикла продаж.',
    images: [],
    dependsOn: [],
    state: 'ready',
    assigneeIds: [],
    checkerIds: [],
    assigneeAccessSection: 'clients',
    source: 'clients',
    syncRef: { source: 'clients', sourceRefId: 'cl_001' },
    createdAt: '2026-09-03T15:40:00.000Z',
  },
  {
    id: 'task_002',
    title: 'Клиент «Захарова Алина Викторовна»: Обсуждение',
    description: 'Довести клиента до следующей стадии цикла продаж.',
    images: [],
    dependsOn: [],
    state: 'ready',
    assigneeIds: [],
    checkerIds: [],
    assigneeAccessSection: 'clients',
    source: 'clients',
    syncRef: { source: 'clients', sourceRefId: 'cl_002' },
    createdAt: '2026-08-20T12:00:00.000Z',
  },
  {
    id: 'task_003',
    title: 'Клиент «Быков Сергей Олегович»: Согласование',
    description: 'Довести клиента до следующей стадии цикла продаж.',
    images: [],
    dependsOn: [],
    state: 'ready',
    assigneeIds: [],
    checkerIds: [],
    assigneeAccessSection: 'clients',
    source: 'clients',
    syncRef: { source: 'clients', sourceRefId: 'cl_003' },
    createdAt: '2026-08-05T09:00:00.000Z',
  },
  {
    id: 'task_004',
    title: 'Клиент «Ковалёва Марина Дмитриевна»: Оплата',
    description: 'Довести клиента до следующей стадии цикла продаж.',
    images: [],
    dependsOn: [],
    state: 'ready',
    assigneeIds: [],
    checkerIds: [],
    assigneeAccessSection: 'clients',
    source: 'clients',
    syncRef: { source: 'clients', sourceRefId: 'cl_004' },
    createdAt: '2026-07-18T10:20:00.000Z',
  },
  {
    id: 'task_005',
    title: 'Обновить прайс-лист на сайте',
    description: 'Актуализировать цены модулей «Ясень» и «Дуб» после пересчёта себестоимости.',
    images: [],
    dependsOn: [],
    state: 'in_progress',
    assigneeIds: ['acc_marketing'],
    checkerIds: ['acc_admin'],
    source: 'manual',
    dueDate: '2026-09-10',
    createdAt: '2026-09-01T11:00:00.000Z',
  },
  {
    id: 'task_006',
    title: 'Заказать бланки договоров в типографии',
    description: 'Ставится в работу после того, как обновлён прайс-лист — в бланке указываются актуальные цены.',
    images: [],
    dependsOn: ['task_005'],
    state: 'not_ready',
    assigneeIds: ['acc_sales'],
    checkerIds: [],
    source: 'manual',
    dueDate: '2026-09-20',
    createdAt: '2026-09-02T09:00:00.000Z',
  },
]
